#UITLEG:
# - Dit configuratiebestand is in TOML formaat, dit wijst zich hopelijk vanzelf.
# - Alle 'icon' velden in deze configuratie verwijzen naar iconen uit Font Awesome 5, zie https://fontawesome.com/icons
# - Alle 'text' velden in deze configuratie voldoen aan Markdown formaat: https://github.github.com/gfm/
# - Alle 'source' velden verwijzen naar fotobestanden in static/img/ , waarbinnen voor elke categorie een subdirectory bestaat.
#   Daarbinnen kan je je foto's uploaden. Let op, bestandsnamen zijn hoofldettergevoelig!

baseURL = "https://gayasaya.nl/"
languageCode = "nl-nl"
title = "Gaya Saya"
theme = "prologue.gayasaya"

description = "Gaya Saya"

[params]
    name = "Gaya Saya"
    description = "Patrick Holsheimer - Edelsmid"
    copyright = "2011-2020 Patrick Holsheimer"
    title = "Gaya Saya"
    subtitle = "Patrick Holsheimer, ambachtelijk edelsmid voor unieke sieraden!"


[params.about]
    title = "Over Gaya Saya"
    icon = "user"
    text = """
De naam **Gaya Saya** is afkomstig uit Indonesië en betekent *Mijn Stijl*

Ik ben Patrick Holsheimer, en zowel voor dames als heren ontwerp ik mijn eigen gemaakte sieraden. Hierdoor heeft u dus altijd een uniek sieraad! Ook is het zelfs mogelijk om uw eigen idee en/of ontwerp bij mij aan te leveren.

Uiteraard kunt u voor reparaties ook bij Gaya Saya terecht.
"""

[[params.social]]
    medium = "email"
    icon = "envelope"
    link = "#"


[[params.categories]]
    title = "Ringen"
    text = "Ik maak ringen voor zowel dames als heren, inclusief uiteraard trouwringen!"
    icon = "ring"

  [[params.categories.items]]
        title = "Zilveren ring met *Micro pavé*"
        source = "Zilveren ring met micro-pavé.jpg"

    [[params.categories.items]]
        title = "Zilveren ring met *vierkante Zirkonia*"
        source = "Zilveren ring met vierkante zetkast.jpg"


    [[params.categories.items]]
        title = "Witgouden ring 14K met **Opaliet**"
        source = "Witgouden 14K ring met Maansteen_1.jpg"

    [[params.categories.items]]
        title = "Zilveren *Solitaire* ring met witte zirkonia"
        source = "Zilveren koningsring met witte zirkonia.jpg"

    [[params.categories.items]]
        title = "Smeedring met *Leopard Jaspis*"
        source = "Smeedring met Jaspis.jpg"

    [[params.categories.items]]
        title = "Zilveren trouwringen met 0.03 karaat Diamant"
        source = "Trouwringen1.JPG"


[[params.categories]]
    title = "Colliers"
    icon = "gem"
    
   [[params.categories.items]]
        title = "Zilveren draad-buis collier met graancirkel en *Zirkonia*"
        source = "Draad-buis colllier.jpg"
  
    



[[params.categories]]
    title = "Broches"
    icon = "gem"

[[params.categories]]
    title = "Hangers"
    icon = "gem"

[[params.categories]]
    title = "Oorbellen"
    icon = "gem"

[[params.categories]]
    title = "Armbanden"
    icon = "gem"
    
 [[params.categories.items]]
        title = "Zilveren armband met Mokume gane en bakslot"
        source = "Armband met scharnier en slot.jpg"


[[params.categories]]
    title = "Speciaal"
    icon = "gem"

