baseURL = "https://gayasaya.nl/"
languageCode = "nl-nl"
title = "Gaya Saya"
theme = "prologue.gayasaya"

description = "Gaya Saya"

[params]
    name = "Gaya Saya"
    description = "Patrick Holsheimer - Edelsmid"
    copyright = "2011-2019 Patrick Holsheimer"
    title = "Gaya Saya"
    subtitle = "Patrick Holsheimer, ambachtelijk edelsmid voor unieke sieraden!"


[params.about]
    title = "Over Gaya Saya"
    text = """
De naam **Gaya Saya** is afkomstig uit Indonesië en betekent *Mijn Stijl*

Ik ben Patrick Holsheimer, en zowel voor dames als heren ontwerp ik mijn eigen gemaakte sieraden. Hierdoor heeft u dus altijd een uniek sieraad! Ook is het zelfs mogelijk om uw eigen idee en/of ontwerp bij mij aan te leveren.

Uiteraard kunt u voor reparaties ook bij Gaya Saya terecht.
"""

[[params.social]]
    medium = "email"
    icon = "envelope"
    link = "#"


[[params.categories]]
    title = "Ringen"
    text = "Ik maak ringen voor zowel dames als heren, inclusief uiteraard trouwringen!"
    icon = "circle-o-notch"

    [[params.categories.items]]
        title = "Witgouden ring 14K met **Opaliet**"
        source = "Witgouden 14K ring met Maansteen_1.jpg"

    [[params.categories.items]]
        title = "Zilveren *Solitaire* ring met witte zirkonia"
        source = "Zilveren koningsring met witte zirkonia.jpg"

    [[params.categories.items]]
        title = "Smeedring met *Leopard Jaspis*"
        source = "Smeedring met Jaspis.jpg"

    [[params.categories.items]]
        title = "Zilveren trouwringen met 0.03 karaat Diamant"
        source = "Trouwringen1.JPG"

[[params.categories]]
    title = "Colliers"
    icon = "circle-o-notch"

[[params.categories]]
    title = "Broches"
    icon = "circle-o-notch"

[[params.categories]]
    title = "Hangars"
    icon = "circle-o-notch"

[[params.categories]]
    title = "Oorbellen"
    icon = "circle-o-notch"

[[params.categories]]
    title = "Armbanden"
    icon = "circle-o-notch"

[[params.categories]]
    title = "Speciaal"
    icon = "th"

