# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Prologue (for GayaSaya)"
license = "Creative Commons Attribution 3.0 Unported"
licenselink = "https://github.com/sethmacleod/prologue/blob/master/LICENSE.md"
description = "Ported theme by HTML5 UP. Prologue is a single page responsive site template with a sticky sidebar."
homepage = "https://github.com/sethmacleod/prologue"
tags = ["responsive", "personal", "portfolio"]
features = ["responsive", "sticky sidebar"]
min_version = 0.18

[author]
  name = "Maarten van Gompel"
  homepage = "https://proycon.anaproy.nl"

[original]
  name = "Seth MacLeod, ported from @ajlkn"
  homepage = "https://www.sethmacleod.com/"

